# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b7737a203a724764b2dd3a90771b2a3"
name = "scalable-investment-app"
application_url = "https://excitement-grow-manitoba-marked.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "meejal.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://excitement-grow-manitoba-marked.trycloudflare.com/auth/callback",
  "https://excitement-grow-manitoba-marked.trycloudflare.com/auth/shopify/callback",
  "https://excitement-grow-manitoba-marked.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
